from .views import *
from django.urls import path, include

urlpatterns = [
    path('auth/', auth, name='auth'),
    path('logout/', logout, name='logout'),
    path('api/check_creds/', check_creds, name='check_creds'),
    path('main/', index, name='index'),
    path('donor-search/', donor_search, name='donor_search'),
    path('donation/register/', donation_register, name='donation_register'),
    path('api/donor/<int:donor_id>/', get_donor_info, name='get_donor_info'),
    path('direction/menu', index_direction, name='index_direction'),
    path('payment/register/', payment_register, name='payment_register'),
    path('payment/search/', payment_search, name='payment_search'),
    path('api/payment/<int:payment_id>/', get_payment_info, name='get_payment_info'),
    path('payment/<int:payment_id>/details/', payment_details, name='payment_details'),
    path('api/donation/<int:donation_id>/', get_donation_info, name='get_donation_info'),
    path('donation-direction/create/', donation_direction_form, name='donation_direction_form'),
    path('donation-direction/save/', donation_direction_create, name='donation_direction_create'),
path('donation-direction/edit/<int:direction_id>/', donation_direction_edit, name='donation_direction_edit'),
path('donation-direction/update/<int:direction_id>/', donation_direction_update, name='donation_direction_update'),
    path('api/donor/<int:donor_id>/', donor_api, name='donor_api'),
    path('api/donor/<int:donor_id>/last_donation/', donor_last_donation_api, name='donor_last_donation_api'),
    path('examination-direction/create/', examination_direction_form, name='examination_direction_form'),
    path('examination-direction/save/', examination_direction_create, name='examination_direction_create'),
    path('blood-analysis-direction/create/', blood_analysis_direction_form, name='blood_analysis_direction_form'),
    path('blood-analysis-direction/save/', blood_analysis_direction_create, name='blood_analysis_direction_create'),
    path('api/donor/<int:donor_id>/last_blood_analysis/', donor_last_blood_analysis_api, name='donor_last_blood_analysis_api'),
    path('directions/', direction_search, name='direction_search'),
    path('donation-direction/view/<int:direction_id>/', donation_direction_view, name='donation_direction_view'),
    path('examination-direction/view/<int:direction_id>/', examination_direction_view,
         name='examination_direction_view'),
path('examination-direction/edit/<int:direction_id>/', examination_direction_edit, name='examination_direction_edit'),
path('examination-direction/update/<int:direction_id>/', examination_direction_update, name='examination_direction_update'),
path('blood-analysis-direction/view/<int:pk>/', blood_analysis_direction_detail, name='blood_analysis_direction_detail'),
path('blood-analysis-direction/<int:pk>/edit/', blood_analysis_direction_edit, name='blood_analysis_direction_edit'),
path('blood-analysis-direction/<int:pk>/update/', blood_analysis_direction_update, name='blood_analysis_direction_update'),
    path('external-direction/create/', external_direction_form, name='external_direction_form'),
    path('external-direction/save/', external_direction_create, name='external_direction_create'),
    path('external-direction/view/<int:direction_id>/', external_direction_view, name='external_direction_view'),
path('external-direction/edit/<int:direction_id>/', external_direction_edit, name='external_direction_edit'),
path('external-direction/update/<int:direction_id>/', external_direction_update, name='external_direction_update'),
    path('donor/<int:donor_id>/medical-card/', donor_medical_card, name='donor_medical_card'),
    path('donation', index_donation, name='donation_menu'),
    path('donation/create/', donation_form, name='donation_form'),
    path('donation/save/', donation_create, name='donation_create'),
    path('donation/view/<int:donation_id>/', donation_view, name='donation_view'),
    path('donation/edit/<int:donation_id>/', donation_edit, name='donation_edit'),
    path('donation/update/<int:donation_id>/', donation_update, name='donation_update'),
    path('donations/', donation_search, name='donation_search'),
# urls.py
    path('payment/<int:payment_id>/upload_application/', upload_payment_application, name='upload_payment_application'),
    path('payment/menu/', index_payment, name='payment_menu'),
    path('payment_applications/<str:document_id>', get_file, name='payment_applications'),
    # path('donor/<int:donor_id>/personal-data/', views.donor_personal_data, name='donor_personal_data'),
    # path('donor/<int:donor_id>/card/', views.donor_card, name='donor_card'),
    # path('donor/<int:donor_id>/schedule-donation/', views.schedule_donation, name='schedule_donation'),
    # path('direction/<int:direction_id>/', views.view_direction, name='view_direction'),
    path('analytics/', analytics_view, name='analytics'),
    path('donor/view/<int:donor_id>/', donor_view, name='donor_view'),
    path('donor/edit/<int:donor_id>/', donor_edit, name='donor_edit'),
    path('donor/create/', donor_create, name='donor_create'),

    path('donor-card/view/<int:card_id>/', donor_card_view, name='donor_card_view'),
    path('donor-card/edit/<int:card_id>/', donor_card_edit, name='donor_card_edit'),
    path('donor-card/create/', donor_card_create, name='donor_card_create'),
]
