# Generated by Django 5.0.3 on 2025-03-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snils', models.CharField(max_length=14, unique=True, verbose_name='СНИЛС')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('blood_group', models.CharField(choices=[('O-', 'O-'), ('O+', 'O+'), ('A-', 'A-'), ('A+', 'A+'), ('B-', 'B-'), ('B+', 'B+'), ('AB-', 'AB-'), ('AB+', 'AB+')], max_length=3, verbose_name='Группа крови')),
                ('rh_factor', models.CharField(choices=[('+', 'Положительный'), ('-', 'Отрицательный')], max_length=1, verbose_name='Rh-фактор')),
                ('kell_factor', models.CharField(choices=[('+', 'Положительный'), ('-', 'Отрицательный')], max_length=1, verbose_name='Kell-фактор')),
                ('last_weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Последний вес (кг)')),
                ('last_pressure', models.CharField(max_length=7, verbose_name='Последнее давление')),
            ],
        ),
    ]
