# Generated by Django 5.0.3 on 2025-03-27 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LinaSiteApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название компонента')),
            ],
        ),
        migrations.AddField(
            model_name='donor',
            name='blood_components',
            field=models.ManyToManyField(blank=True, to='LinaSiteApp.bloodcomponent', verbose_name='Компоненты крови'),
        ),
        migrations.CreateModel(
            name='PeripheralBloodTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_date', models.DateField(verbose_name='Дата предполагаемой донации')),
                ('document_number', models.CharField(max_length=20, verbose_name='Номер документа, удостоверяющего личность')),
                ('donation_type', models.CharField(choices=[('whole_blood', 'Цельная кровь'), ('plasma', 'Плазма'), ('platelets', 'Тромбоциты'), ('erythrocytes', 'Эритроциты'), ('granulocytes', 'Гранулоциты')], max_length=20, verbose_name='Тип донации')),
                ('hemoglobin', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Показатель гемоглобина')),
                ('erythrocytes', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество эритроцитов')),
                ('platelets', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество тромбоцитов')),
                ('leukocytes', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество лейкоцитов')),
                ('albumin', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Альбумин')),
                ('globulin', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Глобулин')),
                ('soe', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='СОЕ')),
                ('hct', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='HCT')),
                ('mcv', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='MCV')),
                ('mch', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='MCH')),
                ('mchc', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='MCHC')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LinaSiteApp.donor', verbose_name='Донор')),
            ],
        ),
    ]
