# Generated by Django 5.0.3 on 2025-03-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LinaSiteApp', '0002_bloodcomponent_donor_blood_components_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='donation_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество донаций'),
        ),
        migrations.AddField(
            model_name='donor',
            name='is_regular',
            field=models.BooleanField(default=False, verbose_name='Штатный донор'),
        ),
    ]
